Repository Leafwing-Studios/Emergence, pull requests merged in 2023-05, with the labels that each got.

#805 Simulate world after generation to let things stabilize before playing
  Cargo.lock
  emergence_game/src/main.rs
  emergence_lib/Cargo.toml
  emergence_lib/src/construction/zoning.rs
  emergence_lib/src/player_interaction/abilities.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/picking.rs
  emergence_lib/src/utils/mod.rs
  emergence_lib/src/utils/noise.rs
  emergence_lib/src/world_gen/mod.rs
  emergence_lib/src/world_gen/organism_generation.rs
  emergence_lib/src/world_gen/terrain_generation.rs
Labels: generation

#809 Update hexx to 0.6
  Cargo.lock
  emergence_lib/Cargo.toml
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/units/actions.rs
Labels: dependencies

#814 Compute and visualize water velocity
  emergence_lib/src/infovis.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/water/water_dynamics.rs
Labels: gameplay, info-viz

#819 Code quality improvements for vector fields
  emergence_lib/src/infovis.rs
Labels: code quality, info-viz

#823 Increase acacia seed energy pool so they actually live to adulthood
  emergence_game/assets/manifests/base_game.structure_manifest.json
Labels: bug, gameplay

#824 Don't emit signals for fluids needed by crafters
  emergence_lib/src/crafting/mod.rs
Labels: bug, gameplay

#828 Visualize water flux
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/infovis.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/water/mod.rs
Labels: info-viz

#829 Don't let FixedUpdate enter a death spiral
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/world_gen/mod.rs
Labels: bug, performance

#830 Improve camera controls under heavy lag
  emergence_lib/src/player_interaction/camera.rs
Labels: polish, player interaction

#831 Reduce risk of oscillations in water dynamics
  emergence_lib/src/water/mod.rs
  emergence_lib/src/water/water_dynamics.rs
  emergence_lib/src/world_gen/mod.rs
Labels: bug

#833 Use correct alpha value for vector field overlay
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/infovis.rs
Labels: polish, info-viz

#832 Make terrain toppers green by default
  emergence_game/assets/icons/terrain/grassy.png
  emergence_game/assets/icons/terrain/grassy.svg
  emergence_game/assets/icons/terrain/swampy.png
  emergence_game/assets/icons/terrain/swampy.svg
  emergence_game/assets/manifests/base_game.terrain_manifest.json
  emergence_game/assets/terrain/grassy.blend
  emergence_game/assets/terrain/grassy.gltf
  emergence_game/assets/terrain/loam.blend
  emergence_game/assets/terrain/muddy.blend
  emergence_game/assets/terrain/muddy.gltf
  emergence_game/assets/terrain/swampy.blend
  emergence_game/assets/terrain/swampy.gltf
  emergence_lib/src/world_gen/mod.rs
Labels: polish, art

#834 Vary soil water properties by soil type
  emergence_game/assets/manifests/base_game.terrain_manifest.json
  emergence_lib/src/terrain/terrain_manifest.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/water/water_dynamics.rs
  emergence_lib/tests/serde_manifests.rs
Labels: gameplay

#835 Display and use normalized light values
  emergence_game/assets/manifests/base_game.recipe_manifest.json
  emergence_lib/src/crafting/recipe.rs
  emergence_lib/src/graphics/atmosphere.rs
  emergence_lib/src/simulation/light.rs
  emergence_lib/src/ui/production_statistics.rs
  emergence_lib/tests/serde_manifests.rs
Labels: polish, info-viz

#837 Add basic shade mechanics
  emergence_lib/src/crafting/mod.rs
  emergence_lib/src/crafting/recipe.rs
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/infovis.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/light/mod.rs
  emergence_lib/src/light/shade.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/ui/production_statistics.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/tests/serde_manifests.rs
Labels: gameplay

#844 Swap to a static sun
  emergence_lib/src/graphics/atmosphere.rs
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/light/mod.rs
  emergence_lib/src/simulation/time.rs
Labels: gameplay, game design

#846 Flesh out shade mechanics
  emergence_game/assets/manifests/base_game.recipe_manifest.json
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_lib/src/crafting/recipe.rs
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/infovis.rs
  emergence_lib/src/light/mod.rs
  emergence_lib/src/light/shade.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/simulation/weather.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/structure_assets.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/world_gen/mod.rs
  emergence_lib/tests/serde_manifests.rs
Labels: gameplay, info-viz

#847 Base evaporation rate on `ReceivedLight`, not weather
  emergence_lib/src/simulation/weather.rs
  emergence_lib/src/water/water_dynamics.rs
Labels: gameplay

#850 Display overlays on top of the water surface
  emergence_game/src/main.rs
  emergence_lib/src/graphics/infovis.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/terrain/commands.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/ui/production_statistics.rs
  emergence_lib/src/water/water_dynamics.rs
Labels: polish, info-viz

#854 Make litter float and be carried by currents
  Cargo.lock
  emergence_game/assets/manifests/base_game.item_manifest.json
  emergence_lib/Cargo.toml
  emergence_lib/src/construction/ghosts.rs
  emergence_lib/src/construction/mod.rs
  emergence_lib/src/construction/terraform.rs
  emergence_lib/src/crafting/inventories.rs
  emergence_lib/src/crafting/item_tags.rs
  emergence_lib/src/crafting/mod.rs
  emergence_lib/src/crafting/recipe.rs
  emergence_lib/src/crafting/workers.rs
  emergence_lib/src/graphics/infovis.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/terrain.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/item_manifest.rs
  emergence_lib/src/items/slot.rs
  emergence_lib/src/light/shade.rs
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/player_interaction/abilities.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/src/terrain/litter.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/ui/status.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/water/roots.rs
  emergence_lib/src/world_gen/mod.rs
  emergence_lib/src/world_gen/organism_generation.rs
  emergence_lib/tests/serde_manifests.rs
Labels: gameplay

#861 Add chutes
  emergence_game/assets/icons/structures/chute.png
  emergence_game/assets/icons/structures/chute.svg
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_game/assets/structures/chute.blend
  emergence_game/assets/structures/chute.gltf
  emergence_lib/src/crafting/inventories.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/logistic_buildings.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/src/terrain/litter.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/water/mod.rs
Labels: gameplay

#869 Increase emitter strength to increase stream velocity
  emergence_lib/src/graphics/infovis.rs
  emergence_lib/src/water/mod.rs
Labels: gameplay

#875 Don't deposit goods up cliffs
  emergence_lib/src/terrain/litter.rs
  emergence_lib/src/water/mod.rs
Labels: bug, gameplay

#876 Take structure height into account for reachability
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/units/actions.rs
Labels: bug, gameplay

#881 Display total count of each item
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/overlay.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/ui/production_statistics.rs
Labels: info-viz

#882 Ensure soil is conserved during terraforming operations
  emergence_lib/src/construction/terraform.rs
  emergence_lib/src/crafting/inventories.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/world_gen/mod.rs
Labels: bug, gameplay

#889 Ensure units are blocked by structures
  emergence_lib/src/simulation/geometry.rs
Labels: bug, gameplay

#888 Don't cancel ghosts by transforming
  emergence_lib/src/simulation/geometry.rs
Labels: polish, gameplay

#904 Make moving and building underwater less frustrating
  emergence_game/assets/icons/goals/breathe.png
  emergence_game/assets/icons/goals/breathe.svg
  emergence_game/assets/manifests/base_game.recipe_manifest.json
  emergence_lib/benches/signals.rs
  emergence_lib/src/construction/ghosts.rs
  emergence_lib/src/construction/zoning.rs
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/organisms/oxygen.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/ui/ui_assets.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/basic_needs.rs
  emergence_lib/src/units/goals.rs
  emergence_lib/src/units/mod.rs
  emergence_lib/src/units/unit_manifest.rs
  emergence_lib/tests/serde_manifests.rs
Labels: polish, gameplay, player interaction

#924 Add simple benchmarks for water dynamics
  emergence_lib/Cargo.toml
  emergence_lib/benches/water.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/terrain/terrain_manifest.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/water/ocean.rs
  emergence_lib/src/water/water_dynamics.rs
Labels: code quality, performance

#926 Accelerate water dynamics by removing WaterTable resource
  emergence_game/assets/manifests/base_game.terrain_manifest.json
  emergence_lib/benches/water.rs
  emergence_lib/src/graphics/overlay.rs
  emergence_lib/src/graphics/terrain.rs
  emergence_lib/src/graphics/water.rs
  emergence_lib/src/organisms/oxygen.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/structures/logistic_buildings.rs
  emergence_lib/src/terrain/commands.rs
  emergence_lib/src/terrain/litter.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/terrain/terrain_manifest.rs
  emergence_lib/src/ui/production_statistics.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/water/emitters.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/water/ocean.rs
  emergence_lib/src/water/roots.rs
  emergence_lib/src/water/water_dynamics.rs
  emergence_lib/src/world_gen/terrain_generation.rs
  emergence_lib/tests/serde_manifests.rs
Labels: performance

#928 Remove abilities and intent system
  design/src/SUMMARY.md
  design/src/glossary.md
  design/src/high-level/game-thesis.md
  design/src/high-level/mechanical-translation.md
  design/src/player-actions/index.md
  design/src/player-actions/intent.md
  design/src/research/hive-mind-upgrades.md
  design/src/steam-page.md
  emergence_game/assets/icons/abilities/amplify.png
  emergence_game/assets/icons/abilities/amplify.svg
  emergence_game/assets/icons/abilities/dampen.png
  emergence_game/assets/icons/abilities/dampen.svg
  emergence_game/assets/icons/abilities/fallow.png
  emergence_game/assets/icons/abilities/fallow.svg
  emergence_game/assets/icons/abilities/flourish.png
  emergence_game/assets/icons/abilities/flourish.svg
  emergence_game/assets/icons/abilities/lure.png
  emergence_game/assets/icons/abilities/lure.svg
  emergence_game/assets/icons/abilities/repel.png
  emergence_game/assets/icons/abilities/repel.svg
  emergence_game/assets/icons/goals/lure.png
  emergence_game/assets/icons/goals/lure.svg
  emergence_game/assets/icons/goals/repel.png
  emergence_game/assets/icons/goals/repel.svg
  emergence_lib/src/construction/zoning.rs
  emergence_lib/src/crafting/mod.rs
  emergence_lib/src/crafting/workers.rs
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/organisms/energy.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/player_interaction/abilities.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/ui/cursor.rs
  emergence_lib/src/ui/intent.rs
  emergence_lib/src/ui/mod.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/ui/select_ability.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/ui/ui_assets.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
Labels: game design

#939 Add tide weed
  emergence_game/assets/icons/structures/tide_weed.png
  emergence_game/assets/icons/structures/tide_weed.svg
  emergence_game/assets/manifests/base_game.item_manifest.json
  emergence_game/assets/manifests/base_game.recipe_manifest.json
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_game/assets/structures/tide_weed.blend
  emergence_game/assets/structures/tide_weed.gltf
  emergence_lib/src/asset_management/manifest/mod.rs
  emergence_lib/src/construction/ghosts.rs
  emergence_lib/src/organisms/energy.rs
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/organisms/vegetative_reproduction.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/world_gen/mod.rs
  emergence_lib/src/world_gen/organism_generation.rs
  emergence_lib/src/world_gen/terrain_generation.rs
  emergence_lib/tests/serde_manifests.rs
Labels: gameplay

#940 Design notes on water
  design/src/SUMMARY.md
  design/src/water.md
Labels: game design

#945 Organize map geometry code
  emergence_lib/benches/signals.rs
  emergence_lib/benches/water.rs
  emergence_lib/src/construction/demolition.rs
  emergence_lib/src/construction/ghosts.rs
  emergence_lib/src/construction/terraform.rs
  emergence_lib/src/construction/zoning.rs
  emergence_lib/src/crafting/mod.rs
  emergence_lib/src/geometry/indexing.rs
  emergence_lib/src/geometry/meshes.rs
  emergence_lib/src/geometry/mod.rs
  emergence_lib/src/geometry/position.rs
  emergence_lib/src/geometry/rotation.rs
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/graphics/overlay.rs
  emergence_lib/src/graphics/terrain.rs
  emergence_lib/src/graphics/water.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/light/shade.rs
  emergence_lib/src/organisms/energy.rs
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/organisms/oxygen.rs
  emergence_lib/src/organisms/vegetative_reproduction.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/picking.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/logistic_buildings.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/structures/structure_assets.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/src/terrain/commands.rs
  emergence_lib/src/terrain/litter.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/terrain/terrain_assets.rs
  emergence_lib/src/ui/production_statistics.rs
  emergence_lib/src/ui/select_structure.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
  emergence_lib/src/units/mod.rs
  emergence_lib/src/units/unit_assets.rs
  emergence_lib/src/utils/noise.rs
  emergence_lib/src/water/emitters.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/water/ocean.rs
  emergence_lib/src/water/roots.rs
  emergence_lib/src/water/water_dynamics.rs
  emergence_lib/src/world_gen/organism_generation.rs
  emergence_lib/src/world_gen/terrain_generation.rs
  emergence_lib/tests/serde_manifests.rs
Labels: code quality

#947 Cache neighbors on MapGeometry
  emergence_lib/src/geometry/indexing.rs
  emergence_lib/src/geometry/position.rs
  emergence_lib/src/geometry/rotation.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/water/water_dynamics.rs
Labels: performance

#950 Further improve signal diffusion performance
  emergence_lib/src/geometry/indexing.rs
  emergence_lib/src/geometry/position.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/world_gen/mod.rs
Labels: performance

#953 Fix signal propagation
  emergence_lib/src/signals.rs
Labels: bug, performance, critical

#954 Basket Crab Proxy Files
  emergence_game/assets/units/BasketCrab_Proxy.blend
  emergence_game/assets/units/BasketCrab_Proxy.gltf
  emergence_game/assets/units/Crab_Proxy.gltf
Labels: art
