Repository Leafwing-Studios/Emergence, pull requests merged in 2023-02, with the labels that each got.

#255 Migrate from bevy_ecs_tilemap to hexx
  deny.toml
  emergence_lib/Cargo.toml
  emergence_lib/examples/hexx_101.rs
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/organisms.rs
  emergence_lib/src/graphics/produce.rs
  emergence_lib/src/graphics/sprites.rs
  emergence_lib/src/graphics/terrain.rs
  emergence_lib/src/graphics/ui/hover_panel.rs
  emergence_lib/src/graphics/ui/intent.rs
  emergence_lib/src/graphics/ui/mod.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/organisms/sessile/fungi.rs
  emergence_lib/src/organisms/sessile/mod.rs
  emergence_lib/src/organisms/sessile/plants.rs
  emergence_lib/src/organisms/units/act.rs
  emergence_lib/src/organisms/units/behavior.rs
  emergence_lib/src/organisms/units/mod.rs
  emergence_lib/src/organisms/units/pathfinding.rs
  emergence_lib/src/player_interaction/abilities.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/organism_details.rs
  emergence_lib/src/player_interaction/tile_selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/signals/configs.rs
  emergence_lib/src/signals/emitters.rs
  emergence_lib/src/signals/mod.rs
  emergence_lib/src/signals/tile_signals.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/simulation/map/filters.rs
  emergence_lib/src/simulation/map/hex_patch.rs
  emergence_lib/src/simulation/map/index.rs
  emergence_lib/src/simulation/map/mod.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/simulation/pathfinding.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/terrain/components.rs
  emergence_lib/src/terrain/entity_map.rs
  emergence_lib/src/terrain/mod.rs
  tools/debug_tools/Cargo.toml
Labels: enhancement, code quality, ui

#260 Get camera mostly working and fix organism render
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/player_interaction/camera.rs
Labels: enhancement, code quality, gameplay, graphics, input, player interaction

#261 Improve camera controls
  emergence_lib/examples/hexx_101.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/structures/mod.rs
Labels: polish, player interaction

#262 Use bevy_mod_raycast to handle tile selection
  deny.toml
  emergence_game/src/main.rs
  emergence_lib/Cargo.toml
  emergence_lib/src/asset_management.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/player_interaction/abilities.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/organism_details.rs
  emergence_lib/src/player_interaction/tile_selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/terrain/mod.rs
Labels: enhancement, graphics, input, player interaction

#266 Update deny.toml
  deny.toml
Labels: build-system

#268 Spawn and despawn zoned organisms
  emergence_lib/src/asset_management.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/organisms/sessile/fungi.rs
  emergence_lib/src/organisms/sessile/mod.rs
  emergence_lib/src/organisms/sessile/plants.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/tile_selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/mod.rs
Labels: enhancement, gameplay, player interaction

#280 Simplify selection controls by using right click to deselect
  emergence_lib/src/player_interaction/selection.rs
Labels: code quality, player interaction

#283 Improve terrain performance by reusing a single hex mesh and scaling it
  emergence_game/src/main.rs
  emergence_lib/src/asset_management.rs
  emergence_lib/src/dev_tools/mod.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/player_interaction/selection.rs
Labels: performance, graphics

#284 Discretize height of terrain
  emergence_lib/src/asset_management.rs
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/terrain/mod.rs
Labels: gameplay, graphics

#290 Show hovered tile location
  emergence_lib/src/asset_management.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/player_interaction/selection.rs
Labels: polish, player interaction

#292 Add area select indicator
  deny.toml
  emergence_lib/Cargo.toml
  emergence_lib/src/asset_management.rs
  emergence_lib/src/player_interaction/selection.rs
Labels: polish, player interaction

#296 Add line select functionality
  emergence_lib/Cargo.toml
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/simulation/geometry.rs
Labels: code quality, player interaction

#299 Refactoring to prepare for ghosts (on zoning and to show cursor)
  emergence_lib/src/organisms/life_cycles.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/organisms/sessile/fungi.rs
  emergence_lib/src/organisms/sessile/mod.rs
  emergence_lib/src/organisms/sessile/plants.rs
  emergence_lib/src/player_interaction/organism_details.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/terrain/mod.rs
Labels: bug, code quality

#302 Remove dependency of check-compiles on check-lints
  .github/workflows/ci.yml
Labels: build-system

#301 Fix typo in cron job
  .github/workflows/udeps.yml
Labels: build-system

#305 Show clipboard contents and location via ghosts
  emergence_game/src/main.rs
  emergence_lib/src/dev_tools/mod.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/structures/mod.rs
Labels: enhancement, performance, player interaction

#307 Add ability to rotate selection
  emergence_lib/src/asset_management/terrain.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/tile_selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/terrain/mod.rs
Labels: enhancement, player interaction

#311 Re-add hover details panel
  emergence_game/src/main.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/organism_details.rs
  emergence_lib/src/ui/hover_panel.rs
  emergence_lib/src/ui/intent.rs
  emergence_lib/src/ui/mod.rs
Labels: enhancement, ui

#316 When one tile is selected, track that organism
  emergence_lib/src/player_interaction/organism_details.rs
  emergence_lib/src/ui/hover_panel.rs
Labels: polish, player interaction

#319 Basic gamepad controls
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/tile_selection.rs
Labels: enhancement, input

#320 Add simple structure selection wheel/hex menu
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/ui/mod.rs
  emergence_lib/src/ui/select_structure.rs
Labels: enhancement, ui, player interaction

#326 Use correct mesh and material for ghosts
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/player_interaction/clipboard.rs
Labels: bug, polish, graphics, player interaction

#338 Use manifest for structures
  emergence_lib/src/asset_management/manifest.rs
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/items/mod.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/ui/select_structure.rs
Labels: code quality, architectural

#340 Refactor asset loading into a trait
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/asset_management/structures.rs
Labels: architectural

#343 Directly control selection radius
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/tile_selection.rs
Labels: polish, player interaction

#346 Use 3D models for ants
  emergence_game/assets/units/ant.gltf
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/asset_management/units.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/organisms/units/behavior.rs
  emergence_lib/src/organisms/units/mod.rs
  emergence_lib/src/simulation/generation.rs
Labels: graphics

#348 Basic unit locomotion
  emergence_lib/src/interactable.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/organisms/units/behavior.rs
  emergence_lib/src/organisms/units/mod.rs
  emergence_lib/src/organisms/units/movement.rs
  emergence_lib/src/player_interaction/organism_details.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/terrain/mod.rs
Labels: enhancement, gameplay

#357 Units can carry, pick up and drop off items
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/units.rs
  emergence_lib/src/items/errors.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/mod.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/organisms/units/behavior.rs
  emergence_lib/src/organisms/units/item_interaction.rs
  emergence_lib/src/organisms/units/mod.rs
  emergence_lib/src/player_interaction/organism_details.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
Labels: enhancement, gameplay

#358 Show recipe details on selection panel
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/player_interaction/organism_details.rs
  emergence_lib/src/ui/mod.rs
  emergence_lib/src/ui/selection_panel.rs
Labels: info-viz

#359 Add the ability to inspect units
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/asset_management/terrain.rs
  emergence_lib/src/asset_management/units.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/units.rs
  emergence_lib/src/organisms/units/behavior.rs
  emergence_lib/src/organisms/units/item_interaction.rs
  emergence_lib/src/organisms/units/mod.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/details.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/organism_details.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/ui/mod.rs
  emergence_lib/src/ui/selection_panel.rs
Labels: ui, player interaction, info-viz

#365 Fix item dropoff
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/organisms/units/behavior.rs
  emergence_lib/src/organisms/units/item_interaction.rs
  emergence_lib/src/organisms/units/mod.rs
  emergence_lib/src/player_interaction/details.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/crafting.rs
Labels: bug, gameplay

#376 Move units code into a top level folder
  emergence_lib/src/asset_management/units.rs
  emergence_lib/src/graphics/units.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/details.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/units/behavior.rs
  emergence_lib/src/units/item_interaction.rs
  emergence_lib/src/units/mod.rs
  emergence_lib/src/units/movement.rs
Labels: code quality

#381 Add cursor contol via keyboard and gamepad
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/mod.rs
Labels: input

#383 Zoning creates ghosts, which are then built by units
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/structures.rs
  emergence_lib/src/graphics/terrain.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/ui/select_structure.rs
  emergence_lib/src/units/behavior.rs
Labels: gameplay

#385 Double-click deslect to clear clipboard
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/mod.rs
Labels: player interaction

#388 Persistently select units and structures
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/asset_management/palette.rs
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/asset_management/terrain.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/structures.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/details.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/tile_selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/ui/selection_panel.rs
Labels: player interaction

#394 Indicator viz cleanup
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/selection.rs
  emergence_lib/src/graphics/structures.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/structures/mod.rs
Labels: code quality, info-viz

#395 Bump hexx to 0.4.2
  .gitignore
  Cargo.lock
  emergence_lib/src/player_interaction/selection.rs
Labels: code quality, dependencies

#396 Display entity data about selection
  emergence_lib/src/player_interaction/selection.rs
Labels: dev-ex, info-viz

#397 Revert "Remove dead code for using materials to show selections"
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/structures.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/structures/mod.rs
Labels: bug, info-viz

#398 Ghost selection
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/ui/selection_panel.rs
Labels: info-viz

#401 Signals 101
  Cargo.lock
  emergence_lib/Cargo.toml
  emergence_lib/src/items/mod.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/ui/selection_panel.rs
  emergence_lib/src/units/behavior.rs
  emergence_lib/src/units/mod.rs
Labels: gameplay

#405 Don't diffuse into structure tiles
  emergence_lib/src/signals.rs
Labels: bug, gameplay

#407 Add neglect field to emitters to ensure automatic load balancing
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/slot.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/structures/mod.rs
Labels: gameplay

#409 Always complete area and line selections correctly
  emergence_lib/src/player_interaction/selection.rs
Labels: bug, player interaction

#410 Add snap camera to selection action
  emergence_lib/src/graphics/structures.rs
  emergence_lib/src/graphics/terrain.rs
  emergence_lib/src/graphics/units.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/simulation/geometry.rs
Labels: player interaction

#412 Improve preview and pipetting behavior
  emergence_lib/src/player_interaction/clipboard.rs
Labels: bug, player interaction

#413 Pipetting captures ghosts
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/simulation/geometry.rs
Labels: bug, player interaction

#416 Improve quality of selection code
  emergence_lib/src/player_interaction/selection.rs
Labels: code quality, player interaction

#430 Camera tweaks
  emergence_lib/src/player_interaction/camera.rs
Labels: code quality, polish, graphics

#431 Sessile organisms overproduce products, rather than dying when inventory is full
  emergence_lib/src/items/errors.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/items/slot.rs
  emergence_lib/src/structures/crafting.rs
Labels: bug, gameplay

#433 Add simple ant hive structure
  emergence_game/assets/CREDITS.md
  emergence_game/assets/structures/ant_hive.gltf
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/items/mod.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/units/behavior.rs
Labels: gameplay

#434 Add tests for item transfers
  emergence_lib/src/items/errors.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/units/behavior.rs
  emergence_lib/src/units/item_interaction.rs
Labels: code quality

#445 Initialize sessile organisms in a random state on world gen
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/items/slot.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/crafting.rs
Labels: generation

#451 Remove noisy error about eating the wrong thing
  emergence_lib/src/units/actions.rs
Labels: code quality, dev-ex

#461 Spawn scenes for structure previews too
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/ghost.rs
Labels: bug, graphics

#462 Swap to a unified ID type
  emergence_lib/src/asset_management/manifest.rs
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/asset_management/units.rs
  emergence_lib/src/graphics/structures.rs
  emergence_lib/src/graphics/units.rs
  emergence_lib/src/items/errors.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/mod.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/items/slot.rs
  emergence_lib/src/organisms/energy.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/ui/select_structure.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
  emergence_lib/src/units/hunger.rs
  emergence_lib/src/units/item_interaction.rs
  emergence_lib/src/units/mod.rs
  emergence_lib/src/units/reproduction.rs
Labels: code quality, architectural

#463 Fix facing directions, especially for units
  emergence_lib/src/simulation/geometry.rs
Labels: bug, polish, graphics

#464 Create and use UnitManifest
  emergence_lib/src/asset_management/manifest.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/units/mod.rs
  emergence_lib/src/units/reproduction.rs
Labels: code quality, architectural

#465 Units only carry one item at a time
  emergence_lib/src/graphics/units.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/item_interaction.rs
  emergence_lib/src/units/mod.rs
Labels: gameplay, game design
