Repository Leafwing-Studios/Emergence, pull requests merged in 2023-04, with the labels that each got.

#647 Use sparse registry for cargo
  .github/workflows/ci.yml
  .github/workflows/dependencies.yml
  .github/workflows/udeps.yml
Labels: automation-and-testing

#646 Load remaining manifests from disk
  emergence_game/assets/manifests/base_game.item_manifest.json
  emergence_game/assets/manifests/base_game.recipe_manifest.json
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_game/assets/manifests/base_game.terrain_manifest.json
  emergence_game/assets/manifests/base_game.unit_manifest.json
  emergence_game/assets/manifests/schema/terrain.schema.json
  emergence_lib/src/asset_management/manifest/identifier.rs
  emergence_lib/src/asset_management/manifest/loader.rs
  emergence_lib/src/asset_management/manifest/mod.rs
  emergence_lib/src/asset_management/manifest/plugin.rs
  emergence_lib/src/asset_management/manifest/raw.rs
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/infovis.rs
  emergence_lib/src/items/errors.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/item_manifest.rs
  emergence_lib/src/items/mod.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/items/slot.rs
  emergence_lib/src/organisms/energy.rs
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/player_interaction/terraform.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/simulation/light.rs
  emergence_lib/src/simulation/time.rs
  emergence_lib/src/structures/construction.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/structures/structure_assets.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/terrain/terrain_assets.rs
  emergence_lib/src/terrain/terrain_manifest.rs
  emergence_lib/src/ui/select_structure.rs
  emergence_lib/src/ui/select_terraforming.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/ui/ui_assets.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/hunger.rs
  emergence_lib/src/units/mod.rs
  emergence_lib/src/units/unit_assets.rs
  emergence_lib/src/units/unit_manifest.rs
  emergence_lib/tests/serde_manifests.rs
Labels: dev-ex, architectural

#657 Add stochastic recipe outputs (and acacia seeds!)
  emergence_game/assets/manifests/base_game.item_manifest.json
  emergence_game/assets/manifests/base_game.recipe_manifest.json
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_game/assets/structures/acacia_seed.gltf
  emergence_game/assets/structures/acacia_seedling.blend
  emergence_game/assets/structures/acacia_seedling.gltf
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/structures/construction.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/tests/serde_manifests.rs
Labels: gameplay

#658 Avoid duplicating construction strategies across life stages
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/construction.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/tests/serde_manifests.rs
Labels: code quality, dev-ex

#659 Make more manifest fields optional
  emergence_game/assets/manifests/base_game.recipe_manifest.json
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/structures/construction.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/tests/serde_manifests.rs
Labels: dev-ex

#664 Allow flexible recipe inputs
  emergence_game/assets/manifests/base_game.item_manifest.json
  emergence_game/assets/manifests/base_game.recipe_manifest.json
  emergence_lib/benches/signals.rs
  emergence_lib/src/asset_management/manifest/mod.rs
  emergence_lib/src/crafting/components.rs
  emergence_lib/src/crafting/item_tags.rs
  emergence_lib/src/crafting/mod.rs
  emergence_lib/src/crafting/recipe.rs
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/item_manifest.rs
  emergence_lib/src/items/mod.rs
  emergence_lib/src/items/slot.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/construction.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/ui/status.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
  emergence_lib/src/units/hunger.rs
  emergence_lib/src/units/reproduction.rs
  emergence_lib/tests/serde_manifests.rs
Labels: gameplay, architectural

#670 Fix some typos
  design/src/high-level/creative-automation-case-studies.md
  design/src/high-level/game-thesis.md
  design/src/high-level/genre-analysis.md
  design/src/high-level/genre-mechanics.md
  design/src/organisms/life-cycles.md
  design/src/production-chains/example-leafcutter.md
  design/src/production-chains/index.md
  design/src/research/genetics.md
  design/src/research/hive-mind-upgrades.md
  emergence_lib/src/asset_management/manifest/identifier.rs
  emergence_lib/src/items/slot.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/ui/production_statistics.rs
  emergence_lib/src/units/actions.rs
Labels: documentation

#666 Terraforming takes work
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_lib/src/construction/demolition.rs
  emergence_lib/src/construction/ghosts.rs
  emergence_lib/src/construction/mod.rs
  emergence_lib/src/construction/terraform.rs
  emergence_lib/src/construction/zoning.rs
  emergence_lib/src/crafting/components.rs
  emergence_lib/src/crafting/mod.rs
  emergence_lib/src/graphics/structures.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/terraform.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/construction.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/structures/structure_assets.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/src/terrain/commands.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/ui/mod.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/ui/select_terraforming.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/ui/status.rs
  emergence_lib/src/ui/ui_assets.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
  emergence_lib/src/units/mod.rs
  emergence_lib/tests/serde_manifests.rs
Labels: gameplay, player interaction

#676 Units can only walk and interact over limited height differences
  emergence_lib/src/construction/demolition.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/units.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/units/actions.rs
Labels: gameplay, game design

#682 Store dropped items on the ground
  emergence_game/assets/manifests/base_game.item_manifest.json
  emergence_lib/src/construction/terraform.rs
  emergence_lib/src/crafting/components.rs
  emergence_lib/src/crafting/mod.rs
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
Labels: gameplay

#687 Display status of terraforming actions
  emergence_lib/src/crafting/components.rs
  emergence_lib/src/ui/status.rs
Labels: info-viz

#693 Add models for litter piles
  emergence_game/assets/litter/partial.blend
  emergence_game/assets/litter/partial.gltf
  emergence_game/assets/litter/pile.blend
  emergence_game/assets/litter/pile.gltf
  emergence_game/assets/produce/tile-food-balls.png
  emergence_game/assets/produce/tile-food-balls.svg
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/terrain.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/terrain/terrain_assets.rs
Labels: polish, info-viz

#695 Pickup junk succesfully
  emergence_lib/src/units/actions.rs
Labels: bug, gameplay

#696 Show current tool using a cursor icon
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/construction/zoning.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/infovis.rs
  emergence_lib/src/player_interaction/abilities.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/picking.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/ui/cursor.rs
  emergence_lib/src/ui/mod.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/ui/select_structure.rs
  emergence_lib/src/ui/select_terraforming.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/ui/status.rs
  emergence_lib/src/ui/ui_assets.rs
  emergence_lib/src/ui/wheel_menu.rs
Labels: polish, ui

#702 Add abilities
  design/src/player-actions/intent.md
  emergence_game/assets/icons/abilities/amplify.png
  emergence_game/assets/icons/abilities/amplify.svg
  emergence_game/assets/icons/abilities/dampen.png
  emergence_game/assets/icons/abilities/dampen.svg
  emergence_game/assets/icons/abilities/fallow.png
  emergence_game/assets/icons/abilities/fallow.svg
  emergence_game/assets/icons/abilities/flourish.png
  emergence_game/assets/icons/abilities/flourish.svg
  emergence_game/assets/icons/abilities/lure.png
  emergence_game/assets/icons/abilities/lure.svg
  emergence_game/assets/icons/abilities/repel.png
  emergence_game/assets/icons/abilities/repel.svg
  emergence_lib/src/construction/ghosts.rs
  emergence_lib/src/construction/zoning.rs
  emergence_lib/src/crafting/components.rs
  emergence_lib/src/crafting/mod.rs
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/organisms/energy.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/player_interaction/abilities.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/intent.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/ui/cursor.rs
  emergence_lib/src/ui/intent.rs
  emergence_lib/src/ui/mod.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/ui/select_ability.rs
  emergence_lib/src/ui/select_structure.rs
  emergence_lib/src/ui/select_terraforming.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/ui/ui_assets.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
  emergence_lib/src/units/mod.rs
Labels: ui, gameplay

#706 Randomize starting hunger on world generation
  emergence_lib/src/organisms/energy.rs
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/units/mod.rs
Labels: polish, generation

#707 Add old age mechanic
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_game/assets/manifests/base_game.unit_manifest.json
  emergence_lib/src/construction/ghosts.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/time.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/units/age.rs
  emergence_lib/src/units/mod.rs
  emergence_lib/src/units/unit_manifest.rs
  emergence_lib/tests/serde_manifests.rs
Labels: bug, gameplay

#710 Improve crowding mechanic by attempting to move away from other units of the same type
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/infovis.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/ui/status.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
Labels: gameplay

#711 Destroy signal that would go out of bounds
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/geometry.rs
Labels: bug, gameplay

#725 Faster diffusion
  Cargo.lock
  emergence_lib/Cargo.toml
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/world_gen/mod.rs
Labels: performance

#738 Add system to dynamically adjust camera background based on sun brightness
  emergence_lib/src/graphics/atmosphere.rs
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/graphics/palette.rs
Labels: graphics

#744 Don't use bitfields for CI
  Cargo.lock
  tools/ci/Cargo.toml
  tools/ci/src/main.rs
Labels: code quality, automation-and-testing

#747 Update CI workflows to match current arguments
  .github/workflows/ci.yml
  tools/ci/src/main.rs
Labels: automation-and-testing

#750 Add paths
  emergence_game/assets/icons/structures/path.png
  emergence_game/assets/icons/structures/path.svg
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_game/assets/structures/path.blend
  emergence_game/assets/structures/path.gltf
  emergence_lib/src/construction/zoning.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/terrain/terrain_manifest.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/tests/serde_manifests.rs
Labels: gameplay

#752 Swap to a retained mode strategy for displaying status
  emergence_lib/src/ui/status.rs
Labels: ui, performance

#765 Fix panic when placing ghost
  Cargo.lock
  emergence_lib/src/lib.rs
  emergence_lib/src/ui/status.rs
  emergence_lib/src/utils/curves.rs
  emergence_lib/src/utils/fallible_commands.rs
  emergence_lib/src/utils/mod.rs
Labels: bug, critical

#767 Add basic water
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/graphics/water.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/organisms/drowning.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/simulation/time.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/world_gen/mod.rs
Labels: gameplay

#777 Make water height continuous
  emergence_lib/src/graphics/water.rs
  emergence_lib/src/organisms/drowning.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/terrain/commands.rs
  emergence_lib/src/water/mod.rs
Labels: bug, gameplay, graphics

#784 Track and visualize the water table on a per-tile basis
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/infovis.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/simulation/time.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/world_gen/mod.rs
Labels: gameplay, info-viz

#787 Water flows downhill and horizontally
  emergence_lib/src/infovis.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/world_gen/mod.rs
Labels: bug, gameplay, info-viz

#792 Add water emitters
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_game/assets/structures/spring.blend
  emergence_game/assets/structures/spring.gltf
  emergence_lib/src/construction/ghosts.rs
  emergence_lib/src/construction/mod.rs
  emergence_lib/src/construction/zoning.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/src/ui/ui_assets.rs
  emergence_lib/src/water/emitters.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/world_gen/mod.rs
  emergence_lib/tests/serde_manifests.rs
Labels: gameplay

#793 Fix water dynamics
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/simulation/time.rs
  emergence_lib/src/simulation/weather.rs
  emergence_lib/src/ui/production_statistics.rs
  emergence_lib/src/water/emitters.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/water/roots.rs
  emergence_lib/src/world_gen/mod.rs
Labels: bug, gameplay

#803 Improve wellspring mechanics and clarity
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_game/assets/structures/spring.blend
  emergence_game/assets/structures/spring.gltf
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/water/emitters.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/water/roots.rs
  emergence_lib/src/world_gen/mod.rs
Labels: gameplay
