Repository Leafwing-Studios/Emergence, pull requests merged in 2023-06, with the labels that each got.

#955 Use basket crab models instead of ants
  emergence_game/assets/icons/items/ant_egg.svg
  emergence_game/assets/icons/items/crab_egg.png
  emergence_game/assets/icons/items/crab_egg.svg
  emergence_game/assets/icons/units/basket_crab.png
  emergence_game/assets/icons/units/basket_crab.svg
  emergence_game/assets/manifests/base_game.item_manifest.json
  emergence_game/assets/manifests/base_game.recipe_manifest.json
  emergence_game/assets/manifests/base_game.structure_manifest.json
  emergence_game/assets/manifests/base_game.unit_manifest.json
  emergence_game/assets/units/BasketCrab_Proxy.blend
  emergence_game/assets/units/BasketCrab_Proxy.gltf
  emergence_game/assets/units/ant.blend
  emergence_game/assets/units/ant.gltf
  emergence_game/assets/units/basket_crab.blend
  emergence_game/assets/units/basket_crab.gltf
  emergence_game/assets/units/basket_crab_no_basket.gltf
  emergence_lib/src/asset_management/manifest/mod.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/structure_assets.rs
  emergence_lib/src/terrain/terrain_assets.rs
  emergence_lib/src/ui/ui_assets.rs
  emergence_lib/src/units/unit_assets.rs
  emergence_lib/src/water/water_dynamics.rs
  emergence_lib/src/world_gen/mod.rs
  emergence_lib/tests/serde_manifests.rs
Labels: code quality, art

#971 Deterministic world gen
  Cargo.lock
  emergence_lib/Cargo.toml
  emergence_lib/src/geometry/rotation.rs
  emergence_lib/src/organisms/energy.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/simulation/rng.rs
  emergence_lib/src/units/age.rs
  emergence_lib/src/units/mod.rs
  emergence_lib/src/utils/noise.rs
  emergence_lib/src/world_gen/mod.rs
  emergence_lib/src/world_gen/organism_generation.rs
  emergence_lib/src/world_gen/terrain_generation.rs
Labels: architectural, generation

#972 Upgrade to hexx 0.7
  Cargo.lock
  emergence_lib/Cargo.toml
  emergence_lib/src/geometry/meshes.rs
  emergence_lib/src/geometry/mod.rs
  emergence_lib/src/geometry/position.rs
  emergence_lib/src/geometry/rotation.rs
  emergence_lib/src/litter.rs
  emergence_lib/src/ui/wheel_menu.rs
  emergence_lib/src/water/mod.rs
Labels: code quality, dependencies

#973 Fix crash on integer overflow in debug mode
  emergence_lib/src/geometry/position.rs
Labels: bug

#976 Fix signals following voxel migration
  emergence_lib/src/geometry/indexing.rs
  emergence_lib/src/graphics/overlay.rs
  emergence_lib/src/ui/selection_details.rs
Labels: bug, gameplay

#978 Make it easier to debug walkable neighbors
  emergence_lib/src/geometry/indexing.rs
  emergence_lib/src/ui/selection_details.rs
Labels: dev-ex

#974 Improve selection and terraforming compatibility with voxel rework
  emergence_lib/src/construction/ghosts.rs
  emergence_lib/src/construction/terraform.rs
  emergence_lib/src/construction/zoning.rs
  emergence_lib/src/geometry/indexing.rs
  emergence_lib/src/geometry/position.rs
  emergence_lib/src/geometry/voxels.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/picking.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/terrain/commands.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/ui/selection_details.rs
Labels: bug, code quality, player interaction

#979 Fix clippy issues
  emergence_lib/src/construction/terraform.rs
  emergence_lib/src/construction/zoning.rs
  emergence_lib/src/geometry/indexing.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/picking.rs
  emergence_lib/src/structures/mod.rs
Labels: code quality

#984 Fix structure construction
  emergence_lib/src/construction/zoning.rs
  emergence_lib/src/structures/commands.rs
Labels: bug

#985 Units no longer get stuck wandering / avoiding indefinitely
  emergence_lib/src/geometry/indexing.rs
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/water/mod.rs
  emergence_lib/src/world_gen/mod.rs
  emergence_lib/src/world_gen/terrain_generation.rs
Labels: bug, critical

#987 Fix structure selection
  emergence_lib/src/geometry/indexing.rs
  emergence_lib/src/geometry/rotation.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/ui/selection_details.rs
Labels: bug, player interaction
