Repository Leafwing-Studios/Emergence, pull requests merged in 2023-03, with the labels that each got.

#472 Clipboard copies recipes
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/ui/select_structure.rs
Labels: gameplay, player interaction

#476 Each structures can only be built on certain terrain types
  emergence_lib/src/asset_management/palette.rs
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/structures.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/ghost.rs
  emergence_lib/src/structures/mod.rs
Labels: code quality, gameplay, graphics

#485 Add impatience mechanic again
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
  emergence_lib/src/units/impatience.rs
  emergence_lib/src/units/mod.rs
Labels: gameplay

#486 Only care about selection when terrain is selected
  emergence_lib/src/player_interaction/zoning.rs
Labels: polish, player interaction

#487 Remove neglect mechanic
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/ghost.rs
Labels: gameplay, game design

#488 Ensure structure selection order is consistent
  emergence_lib/src/ui/select_structure.rs
Labels: bug, ui

#495 Add initial custom models
  .gitignore
  emergence_game/assets/CREDITS.md
  emergence_game/assets/structures/acacia.blend
  emergence_game/assets/structures/acacia.gltf
  emergence_game/assets/structures/ant_hive.blend
  emergence_game/assets/structures/ant_hive.gltf
  emergence_game/assets/structures/hatchery.blend
  emergence_game/assets/structures/hatchery.gltf
  emergence_game/assets/structures/leuco.blend
  emergence_game/assets/structures/leuco.gltf
Labels: art

#500 Upgrade to Bevy 0.10
  Cargo.lock
  deny.toml
  emergence_game/Cargo.toml
  emergence_game/src/main.rs
  emergence_lib/Cargo.toml
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/player_interaction/abilities.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/intent.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/ui/mod.rs
  emergence_lib/src/ui/selection_panel.rs
  emergence_lib/src/units/mod.rs
  tools/debug_tools/Cargo.toml
  tools/debug_tools/src/lib.rs
Labels: dependencies

#503 Update hexx dependency to new release
  Cargo.lock
  deny.toml
  emergence_lib/Cargo.toml
Labels: dependencies

#504 Camera rotation fix
  emergence_lib/src/player_interaction/camera.rs
Labels: bug, graphics

#505 Improve signal and action logic to reduce cases of stuck ants
  emergence_lib/src/asset_management/manifest.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/units/actions.rs
Labels: bug, gameplay, game design

#510 Add basic benchmark for signal diffusion
  Cargo.lock
  emergence_lib/Cargo.toml
  emergence_lib/benches/signals.rs
  emergence_lib/src/asset_management/manifest/emergence_markers.rs
  emergence_lib/src/asset_management/manifest/identifier.rs
  emergence_lib/src/asset_management/manifest/mod.rs
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/geometry.rs
Labels: performance

#513 Add a "keep clear" zoning option
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/construction.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
  emergence_lib/src/units/mod.rs
Labels: gameplay, player interaction

#516 Use custom filtered array iterator to avoid allocs
  emergence_lib/src/filtered_array_iter.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/simulation/geometry.rs
Labels: performance

#517 Use HashMap::entry api to speed up lookups
  emergence_lib/src/signals.rs
Labels: performance

#518 Remove unecessary pending maps in diffuse
  emergence_lib/src/signals.rs
Labels: performance

#521 Loading manifests from files
  Cargo.lock
  emergence_game/assets/manifests/items.manifest.json
  emergence_game/assets/manifests/schema/items.schema.json
  emergence_lib/Cargo.toml
  emergence_lib/src/asset_management/manifest/identifier.rs
  emergence_lib/src/asset_management/manifest/loader.rs
  emergence_lib/src/asset_management/manifest/mod.rs
  emergence_lib/src/asset_management/manifest/plugin.rs
  emergence_lib/src/asset_management/manifest/raw.rs
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/items/mod.rs
Labels: dev-ex, architectural

#498 Add and use terrain topper models
  .gitattributes
  emergence_game/assets/structures/acacia.blend
  emergence_game/assets/structures/ant_hive.blend
  emergence_game/assets/structures/hatchery.blend
  emergence_game/assets/structures/leuco.blend
  emergence_game/assets/terrain/base_terrain_topper.blend
  emergence_game/assets/terrain/base_terrain_topper.gltf
  emergence_game/assets/terrain/loam.blend
  emergence_game/assets/terrain/loam.gltf
  emergence_game/assets/terrain/muddy.blend
  emergence_game/assets/terrain/muddy.gltf
  emergence_game/assets/terrain/rocky.blend
  emergence_game/assets/terrain/rocky.gltf
  emergence_lib/src/asset_management/manifest/emergence_markers.rs
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/asset_management/palette.rs
  emergence_lib/src/asset_management/terrain.rs
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/selection.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/units/actions.rs
Labels: graphics, art

#526 Improve translucency for ghosts and tile selections
  emergence_lib/src/asset_management/palette.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/structures/construction.rs
Labels: polish, graphics

#528 Add hex menu backgrounds
  emergence_game/assets/ui/hex-menu-background.png
  emergence_game/assets/ui/hex-menu-background.svg
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/asset_management/ui.rs
  emergence_lib/src/ui/select_structure.rs
Labels: ui, art

#529 Add icons for structures and use in menu
  emergence_game/assets/icons/structures/acacia.png
  emergence_game/assets/icons/structures/acacia.svg
  emergence_game/assets/icons/structures/ant_hive.png
  emergence_game/assets/icons/structures/ant_hive.svg
  emergence_game/assets/icons/structures/hatchery.png
  emergence_game/assets/icons/structures/hatchery.svg
  emergence_game/assets/icons/structures/leuco.png
  emergence_game/assets/icons/structures/leuco.svg
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/asset_management/ui.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/ui/select_structure.rs
Labels: ui, art

#530 Add shadows
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/player_interaction/camera.rs
Labels: polish, graphics

#533 Add day-night cycle
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/simulation/time.rs
Labels: graphics

#535 Fix height of objects
  emergence_game/assets/units/ant.blend
  emergence_game/assets/units/ant.gltf
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/units/actions.rs
Labels: bug, graphics, art

#541 Add a moon
  emergence_lib/src/asset_management/palette.rs
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/simulation/time.rs
  emergence_lib/src/ui/production_statistics.rs
Labels: polish, graphics, info-viz

#542 Animate celestial body illuminance
  emergence_lib/src/graphics/lighting.rs
Labels: graphics, animation

#544 Add link to Discussions
  README.md
Labels: documentation, meta

#545 Disable shadows on ghosts and previews
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/structures.rs
Labels: polish, graphics

#546 Display human readable names for `Id` types
  emergence_lib/benches/signals.rs
  emergence_lib/src/asset_management/manifest/identifier.rs
  emergence_lib/src/asset_management/manifest/mod.rs
  emergence_lib/src/asset_management/manifest/raw.rs
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/asset_management/terrain.rs
  emergence_lib/src/asset_management/ui.rs
  emergence_lib/src/asset_management/units.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/mod.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/items/slot.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/ui/selection_panel.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
  emergence_lib/src/units/hunger.rs
  emergence_lib/src/units/item_interaction.rs
  emergence_lib/src/units/mod.rs
  emergence_lib/src/units/reproduction.rs
Labels: dev-ex, info-viz

#547 Add the ability to pause the game
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/player_interaction/intent.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/simulation/time.rs
  emergence_lib/src/structures/construction.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/mod.rs
Labels: gameplay, player interaction, architectural

#553 Mark single structures for demolition
  emergence_lib/src/player_interaction/zoning.rs
Labels: gameplay

#556 Add basic terraforming
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/terraform.rs
  emergence_lib/src/player_interaction/zoning.rs
Labels: gameplay

#561 Handle when hovered tile is None more gracefully during selection
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/terraform.rs
Labels: bug, player interaction

#567 Don't animate light intensity
  emergence_lib/src/graphics/lighting.rs
Labels: grab-bag, polish, graphics

#571 Fix previews
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/structures/commands.rs
Labels: bug, polish, player interaction

#581 Improve asset loading developer experience
  emergence_game/assets/manifests/items.manifest.json
  emergence_lib/src/asset_management/manifest/plugin.rs
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/asset_management/terrain.rs
  emergence_lib/src/asset_management/ui.rs
  emergence_lib/src/asset_management/units.rs
Labels: code quality, dev-ex

#582 Add a storage mechanic and structure
  emergence_game/assets/icons/structures/storage.png
  emergence_game/assets/icons/structures/storage.svg
  emergence_game/assets/structures/storage.blend
  emergence_game/assets/structures/storage.gltf
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/asset_management/ui.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
Labels: gameplay, art

#584 Read structure and terrain names from manifest
  emergence_lib/src/asset_management/manifest/emergence_markers.rs
  emergence_lib/src/asset_management/manifest/mod.rs
  emergence_lib/src/asset_management/manifest/plugin.rs
  emergence_lib/src/asset_management/manifest/structure.rs
  emergence_lib/src/asset_management/manifest/terrain.rs
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/asset_management/structures.rs
  emergence_lib/src/asset_management/terrain.rs
  emergence_lib/src/asset_management/ui.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/terrain/mod.rs
Labels: dev-ex, architectural

#589 Add basic lifecycles
  emergence_game/assets/structures/acacia.blend
  emergence_game/assets/structures/acacia.gltf
  emergence_game/assets/structures/acacia_seed.blend
  emergence_game/assets/structures/acacia_seed.gltf
  emergence_game/assets/structures/acacia_sprout.blend
  emergence_game/assets/structures/acacia_sprout.gltf
  emergence_lib/src/asset_management/manifest/structure.rs
  emergence_lib/src/asset_management/ui.rs
  emergence_lib/src/organisms/energy.rs
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/construction.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/ui/select_structure.rs
  emergence_lib/src/ui/selection_panel.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/mod.rs
Labels: gameplay, architectural

#590 Life cycles now support elapsed time
  emergence_lib/src/asset_management/manifest/structure.rs
  emergence_lib/src/organisms/energy.rs
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/simulation/time.rs
Labels: code quality, gameplay

#592 Track total light and require it for photosynthesis
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/simulation/light.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/simulation/time.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/ui/production_statistics.rs
Labels: gameplay, info-viz

#596 Improve wandering behavior by making multimodal
  emergence_lib/src/signals.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
  emergence_lib/src/units/hunger.rs
  emergence_lib/src/units/mod.rs
Labels: gameplay, game design

#599 Reduce clumping by increasing wander time based on unit density
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/ui/selection_panel.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
  emergence_lib/src/units/hunger.rs
  emergence_lib/src/units/mod.rs
Labels: gameplay

#602 Reduce density effect on wandering
  emergence_lib/src/units/goals.rs
Labels: gameplay

#610 Update to released version of bevy_mod_raycast
  Cargo.lock
  emergence_game/Cargo.toml
  emergence_game/src/main.rs
  emergence_lib/Cargo.toml
  emergence_lib/src/asset_management/manifest/emergence_markers.rs
  emergence_lib/src/asset_management/manifest/identifier.rs
  emergence_lib/src/structures/construction.rs
Labels: dependencies

#611 Vary signal overlay color by signal kind
  emergence_lib/src/asset_management/palette.rs
  emergence_lib/src/infovis.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/ui/overlay.rs
Labels: info-viz

#613 Visualize status of units and workers
  Cargo.lock
  emergence_lib/Cargo.toml
  emergence_lib/src/asset_management/palette.rs
  emergence_lib/src/ui/mod.rs
  emergence_lib/src/ui/status.rs
Labels: info-viz

#616 Improve keyboard and camera controls
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/ui/select_terraforming.rs
Labels: polish, player interaction

#618 Add overlay to show most important signals
  emergence_lib/src/asset_management/palette.rs
  emergence_lib/src/infovis.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/ui/overlay.rs
Labels: info-viz

#619 Add the ability to follow units with the camera
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/ui/mod.rs
  emergence_lib/src/ui/selection_details.rs
Labels: player interaction, info-viz

#624 Use released version of bevy_mod_billboard
  Cargo.lock
  emergence_lib/Cargo.toml
Labels: dependencies

#626 Add multi-tile structures
  emergence_game/assets/structures/ant_hive.blend
  emergence_game/assets/structures/ant_hive.gltf
  emergence_lib/src/asset_management/manifest/structure.rs
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/construction.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/units/actions.rs
Labels: code quality, gameplay, architectural

#630 Allow users to visualize status of structures and units seperately
  emergence_lib/src/ui/status.rs
Labels: polish, info-viz

#632 Swap to borderless full screen as default mode
  emergence_game/src/main.rs
Labels: bug, graphics, hardware-specific

#645 Disable depth culling of status displays
  Cargo.lock
  emergence_lib/Cargo.toml
  emergence_lib/src/ui/status.rs
Labels: grab-bag, dependencies, info-viz

#644 Reorganize asset loading code
  Cargo.lock
  emergence_lib/src/asset_management/manifest/emergence_markers.rs
  emergence_lib/src/asset_management/manifest/mod.rs
  emergence_lib/src/asset_management/manifest/plugin.rs
  emergence_lib/src/asset_management/manifest/raw.rs
  emergence_lib/src/asset_management/mod.rs
  emergence_lib/src/graphics/atmosphere.rs
  emergence_lib/src/graphics/lighting.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/palette.rs
  emergence_lib/src/graphics/units.rs
  emergence_lib/src/infovis.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/item_manifest.rs
  emergence_lib/src/items/mod.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/items/slot.rs
  emergence_lib/src/organisms/energy.rs
  emergence_lib/src/organisms/lifecycle.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/clipboard.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/selection.rs
  emergence_lib/src/player_interaction/terraform.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/signals.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/geometry.rs
  emergence_lib/src/structures/commands.rs
  emergence_lib/src/structures/construction.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/src/structures/structure_assets.rs
  emergence_lib/src/structures/structure_manifest.rs
  emergence_lib/src/terrain/mod.rs
  emergence_lib/src/terrain/terrain_assets.rs
  emergence_lib/src/terrain/terrain_manifest.rs
  emergence_lib/src/ui/mod.rs
  emergence_lib/src/ui/overlay.rs
  emergence_lib/src/ui/select_structure.rs
  emergence_lib/src/ui/select_terraforming.rs
  emergence_lib/src/ui/selection_details.rs
  emergence_lib/src/ui/status.rs
  emergence_lib/src/ui/ui_assets.rs
  emergence_lib/src/ui/wheel_menu.rs
  emergence_lib/src/units/actions.rs
  emergence_lib/src/units/goals.rs
  emergence_lib/src/units/hunger.rs
  emergence_lib/src/units/item_interaction.rs
  emergence_lib/src/units/mod.rs
  emergence_lib/src/units/reproduction.rs
  emergence_lib/src/units/unit_assets.rs
  emergence_lib/src/units/unit_manifest.rs
Labels: code quality, architectural
