Repository Leafwing-Studios/Emergence, pull requests merged in 2023-01, with the labels that each got.

#179 Zoning 101
  design/src/SUMMARY.md
  design/src/glossary.md
  design/src/player-actions/index.md
  design/src/player-actions/informational-tools.md
  design/src/player-actions/pheromones.md
  design/src/player-actions/selection-tools.md
  design/src/player-actions/terraforming.md
  design/src/player-actions/zoning.md
  design/src/production-chains/recipes.md
  design/src/signals/configuring-properties.md
  design/src/signals/index.md
Labels: game design

#181 Intent and abilties 101
  design/src/SUMMARY.md
  design/src/glossary.md
  design/src/high-level/game-thesis.md
  design/src/high-level/mechanical-translation.md
  design/src/player-actions/index.md
  design/src/player-actions/intent.md
  design/src/player-actions/pheromones.md
  design/src/research/hive-mind-upgrades.md
  design/src/steam-page.md
  emergence_lib/src/graphics/ui/intent.rs
  emergence_lib/src/graphics/ui/mod.rs
  emergence_lib/src/graphics/ui/pheromone.rs
Labels: game design

#180 Vendor pancam
  emergence_lib/Cargo.toml
  emergence_lib/src/camera.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/lib.rs
  tools/debug_tools/src/lib.rs
Labels: code quality, dependencies

#185 Add loader and noob-trap
  design/src/glossary.md
Labels: documentation, game design

#186 Analysis of production chains
  design/src/SUMMARY.md
  design/src/production-chains/end-products.md
  design/src/production-chains/index.md
  design/src/production-chains/intermediates.md
  design/src/production-chains/recipes.md
Labels: game design

#141 Add `cargo-deny` checks
  .github/workflows/dependencies.yml
  deny.toml
  emergence_game/Cargo.toml
  emergence_lib/Cargo.toml
Labels: build-system, blocked

#199 Refactor structures module
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/organisms/structures.rs
  emergence_lib/src/organisms/structures/fungi.rs
  emergence_lib/src/organisms/structures/mod.rs
  emergence_lib/src/organisms/structures/plants.rs
  emergence_lib/src/simulation/generation.rs
Labels: code quality, dev-ex

#201 Add very simple implementation of Acacia plant
  emergence_lib/src/items.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/organisms/structures/crafting.rs
  emergence_lib/src/organisms/structures/mod.rs
  emergence_lib/src/organisms/structures/plants.rs
  emergence_lib/src/simulation/generation.rs
Labels: prototype, gameplay

#188 Leafcutter prototype recipe chain
  design/src/SUMMARY.md
  design/src/glossary.md
  design/src/logistics/index.md
  design/src/logistics/signals/configuring-properties.md
  design/src/logistics/signals/index.md
  design/src/organisms/index.md
  design/src/organisms/life-cycles.md
  design/src/organisms/sessile-organisms.md
  design/src/organisms/units.md
  design/src/player-actions/intent.md
  design/src/production-chains/example-leafcutter.md
  design/src/production-chains/index.md
Labels: game design

#215 Decouple structures and organisms
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/organisms/sessile/fungi.rs
  emergence_lib/src/organisms/sessile/mod.rs
  emergence_lib/src/organisms/sessile/plants.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/mod.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/src/structures/mod.rs
  emergence_lib/tests/structure_viability.rs
Labels: code quality

#216 Clean up old biomass related code
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/organisms/sessile/plants.rs
  emergence_lib/src/structures/mod.rs
Labels: code quality

#217 Basic skeleton for life cycle code
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/items.rs
  emergence_lib/src/organisms/life_cycles.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/organisms/sessile/fungi.rs
  emergence_lib/src/organisms/sessile/mod.rs
  emergence_lib/src/organisms/sessile/plants.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/structures/crafting.rs
Labels: enhancement, code quality

#204 Add info panel prototype
  emergence_game/assets/fonts/FiraSans-Medium.ttf
  emergence_lib/src/cursor.rs
  emergence_lib/src/graphics/mod.rs
  emergence_lib/src/graphics/ui/hover_panel.rs
  emergence_lib/src/graphics/ui/mod.rs
  emergence_lib/src/hive_mind.rs
  emergence_lib/src/items.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/organisms/organism_details.rs
  emergence_lib/src/structures/crafting.rs
  emergence_lib/tests/structure_viability.rs
Labels: ui

#221 Improve CI times
  .github/workflows/ci.yml
  .github/workflows/design-book.yml
Labels: build-system

#222 Lifecycle brainstorming
  emergence_lib/src/organisms/life_cycles.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/organisms/sessile/fungi.rs
  emergence_lib/src/organisms/sessile/plants.rs
Labels: enhancement, game design

#227 Fix error with wrong commit hash for bevy-trait-query
  emergence_lib/Cargo.toml
Labels: build-system

#230 Add tests to item and inventory functionality
  emergence_lib/src/items.rs
  emergence_lib/src/items/count.rs
  emergence_lib/src/items/errors.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/mod.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/items/slot.rs
  emergence_lib/src/organisms/life_cycles.rs
  emergence_lib/src/organisms/organism_details.rs
  emergence_lib/src/organisms/sessile/mod.rs
  emergence_lib/src/organisms/sessile/plants.rs
  emergence_lib/src/structures/crafting.rs
Labels: code quality

#232 Cleanup and unify camera code
  emergence_lib/src/camera.rs
Labels: code quality

#236 Item and recipe manifests
  emergence_lib/Cargo.toml
  emergence_lib/src/graphics/ui/hover_panel.rs
  emergence_lib/src/items/inventory.rs
  emergence_lib/src/items/mod.rs
  emergence_lib/src/items/recipe.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/manifest.rs
  emergence_lib/src/organisms/organism_details.rs
  emergence_lib/src/organisms/sessile/mod.rs
  emergence_lib/src/organisms/sessile/plants.rs
  emergence_lib/src/structures/crafting.rs
Labels: enhancement, dev-ex

#235 Basic tile selection
  emergence_game/src/main.rs
  emergence_lib/src/graphics/ui/hover_panel.rs
  emergence_lib/src/lib.rs
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/hive_mind.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/organism_details.rs
  emergence_lib/src/player_interaction/tile_selection.rs
  emergence_lib/src/signals/configs.rs
  emergence_lib/src/signals/map_overlay.rs
  emergence_lib/src/signals/mod.rs
  emergence_lib/src/signals/tile_signals.rs
Labels: enhancement, code quality, ui

#240 Zoning prototype
  emergence_lib/src/organisms/mod.rs
  emergence_lib/src/organisms/sessile/fungi.rs
  emergence_lib/src/organisms/sessile/plants.rs
  emergence_lib/src/player_interaction/camera.rs
  emergence_lib/src/player_interaction/cursor.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/organism_details.rs
  emergence_lib/src/player_interaction/tile_selection.rs
  emergence_lib/src/player_interaction/zoning.rs
Labels: enhancement, ui

#248 Clean up draft pheromone/intent code
  emergence_lib/src/organisms/units/act.rs
  emergence_lib/src/organisms/units/mod.rs
  emergence_lib/src/player_interaction/abilities.rs
  emergence_lib/src/player_interaction/hive_mind.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/signals/configs.rs
  emergence_lib/src/signals/emitters.rs
Labels: code quality

#249 Cleanup code around map indexes
  emergence_lib/src/organisms/units/act.rs
  emergence_lib/src/organisms/units/pathfinding.rs
  emergence_lib/src/signals/mod.rs
  emergence_lib/src/simulation/generation.rs
  emergence_lib/src/simulation/map/filters.rs
  emergence_lib/src/simulation/map/hex_patch.rs
  emergence_lib/src/simulation/map/index.rs
  emergence_lib/src/simulation/map/mod.rs
  emergence_lib/src/simulation/pathfinding.rs
  emergence_lib/src/terrain/entity_map.rs
Labels: documentation, code quality

#250 Track and store intent
  emergence_lib/Cargo.toml
  emergence_lib/src/organisms/units/act.rs
  emergence_lib/src/player_interaction/abilities.rs
  emergence_lib/src/player_interaction/intent.rs
  emergence_lib/src/player_interaction/mod.rs
  emergence_lib/src/player_interaction/zoning.rs
  emergence_lib/src/signals/configs.rs
  emergence_lib/src/signals/emitters.rs
  emergence_lib/src/signals/mod.rs
  emergence_lib/src/signals/tile_signals.rs
Labels: enhancement, code quality, player interaction
